sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cyYpx1OUyNy7ecVfWEyT58zLgAsjX//37DQFtGnK6NBZuozaMqB+8TVVENEh5PKKkKREaRi0emVFxc/UZVGiPhmZvcduuGrTe5A8f5xfFXdt9v0Gcb4Gv/PlJ5PKsJAOUbuhePQCgYDL0/hSbwzCabPiNp67SwwgnupRPwq4qEw/mHD9ABv9tOmep67WdYlvNdtY70nDIv/4uRz696LlGhWbIezARXUIkANelcOrDouoWKrH52We0X0TO5CtkIKEBa3JiVQ0gIMr+OcJ72TecEjIcM1IZOKoDCSmmekbJU/+s2gwBryP+nQrBEf4TUSt45kllHD/QXsfXGzSgS/iIXF9hmFiOqssakNBFObkEElzrwfrC/WNbBEdPr+jOv3c0aMRFpgjUdiKrSPPenOBPO7xokcDrToXwTEBqjaZnwp6wBcD8o1D2v2eoyKmskTC0VWpMwIPvBcWyT0rCSHpjgQqdJU4gJR6fgMzAUfUNtUXBAs5vqCJ3Rn6OrJlxXMBbEUQ47rgCvkuEJLachoaT+jTH6DJ6cS2ljCUXNLkvBmUU/peZBIM+LIfA4gIAlg4AiT1ZBTPlABup9nwmAlRcbZ9apPm8sypotWsjhfeeWWNtIsxU/vsB1cC/YG3wgFVeDlsEVCRTK7NaB2vp6B0h+n1AVPwwyqqKnNFCAw6ZiY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Unseen-World-and-Other-Essays_1486
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy